### ISSUE TITLE
0.0V and 0.0A sometimes shown as -0.0V or -0.0A

### ISSUE THREAD

**Issue by danielbriggs** [eez-open/modular-psu-firmware#100]
I'm sure it's a rounding fragment, or floating point issue, but often when the display is reading "0V" or "0A" it's displaying as "-0.0V or "-0.0A" this seems a bit illogical, so any way to clamp it to remove the minus when it's at zero (or as close as possible). Or am I being too picky? ^_^

**Comment by prasimix** [comment]
Fixed
