### ISSUE TITLE
Raw socket (TCP) connection issues

### ISSUE THREAD

**Issue by mvladic** [eez-open/modular-psu-firmware#102]
We found two issues with raw socket connection from client to BB3:

- [x] It seams that small delay is required between connect and first send command on the client side. Otherwise, BB3 will execute the command but it will not detect that connection is closed. This works:

```
connect
delay
send command
close
```

but, this doesn't (BB3 doesn't detect connection close):

```
connect
send command
close
```

@Wolfsbane reported:

> After figuratively smacking my head into the wall it occurred to me that one difference between copying and pasting versus script running was the time between function calls. On a hunch I added a delay between connect() and sendall(). Turns out that in my setup a minimum of 0.8ms delay is needed between the two commands. At 0.7ms the problem shows back up. But at 0.8ms the problem disappears :man_shrugging_tone1:
> 
> ```
> import socket
> from time import sleep
> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
> s.connect(('192.168.1.200', 5025))
> sleep(0.0008)
> s.sendall(b'SYST:BEEP\n')
> s.close()
> ```

- [x] BB3 should clear (or flush) the buffer when connection with the client is closed. So, the new connection will start with empty buffer.

@IanScottJohnston reported:

> It seems I have trouble sending TCPIP SOCKET commands to the BB3 using VB. I think my issue is a terminator problem (or related).
> If I send a command, to turn off Ch.1 for example, it is NOT actioned, but if I then reset the connection and restart it again (from my app) the previous command is then actioned, CH.1 turns off.
> If I built in a terminator into the string "\n" for example it doesn't help.
> AFAIK, with raw socket there is no "clear" command  so no way to flush devices' buffers after an error, no way to recover from errors other that reset the connection. 
> Very curious!
>

**Comment by prasimix** [comment]
Fixed
