### ISSUE TITLE
Unable to raise OCP limit

### ISSUE THREAD

**Issue by gojimmypi** [eez-open/modular-psu-firmware#105]
I set the upper limit to 50mA on Ch 1 of DCP405. Then I wanted to raise that limit:

![image](https://user-images.githubusercontent.com/13059545/97787957-954ceb80-1b72-11eb-8b26-9be2eb7265af.png)

This occurs on both 1.3.2 and 1.4

**Comment by prasimix** [comment]
This is not a bug. You're in low current mode that is indicated with suggested limit 0 A - 50 mA and you have to switch current mode to High or Best.
