### ISSUE TITLE
Poor encoder control for PWM in v1.4

### ISSUE THREAD

**Issue by electrokean** [eez-open/modular-psu-firmware#110]
In FW 1.3.2 the rotary encoder works well for adjusting frequency and duty cycle of the DOUT2 PWM feature.
With the changes in #69 and FW 1.4, the encoder is way too sensitve on these fields.
It isn't improved at all by adjusting the encoder sensitivy settings.

**Comment by prasimix** [comment]
We have to check encoder usability on all other places.

**Comment by prasimix** [comment]
When PWM frequency is changed with encoder, use different sensitivity for Hz range and kHz range.

**Comment by prasimix** [comment]
Improved, but possibly not optimal. Open a new issue if further improvements are expected.
