### ISSUE TITLE
Add customisable boot logo

### ISSUE THREAD

**Issue by danielbriggs** [eez-open/modular-psu-firmware#111]
Of course totally useless, but would nice to set a custom boot logo. :)
Totally a low priority

_Note: if jpg image is used it has to be 480px wide_

**Comment by mvladic** [comment]
Maximal resolution is 480x120. It will accept smaller images. Supported file formats are jpg and bmp.

**Comment by prasimix** [comment]
Bitmap name has to be logo.jpg (or logo.bmp) and it has to be stored in root folder on the SD card.

**Comment by prasimix** [comment]
We still have issue with artifacts in the lower right corner of jpg image:

![DSC03683](https://user-images.githubusercontent.com/15106476/98436688-a56a4b00-20dd-11eb-802b-e374d419850a.JPG)

**Comment by prasimix** [comment]
Fixed
