### ISSUE TITLE
Notification when screenshot is taken

### ISSUE THREAD

**Issue by danielbriggs** [eez-open/modular-psu-firmware#112]
More a suggestion than a bug:
If you have the "Sound" option set to off (as I hate the beeps), then when you take a screenshot, there is not obvious/visible way the BB3 has actually done it + saved it sucessfully.
Maybe some sort of banner / icon / overlay that says "Screenshot Taken" or something really simple + obvious that appears for a few seconds?

[With the sound unmuted, there is a nice "camera" noise, which is a nice addition] :-)

**Comment by prasimix** [comment]
Change to "Screenshot taken", currently is "Screenshot Taken"

**Comment by danielbriggs** [comment]
Or even "Screenshot saved"?

**Comment by prasimix** [comment]
Fixed
