### ISSUE TITLE
SCPI DLOG settings change back to default after each trigger.

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#116]
The settings for functions to log, DLOG sample interval, DLOG time to log and DLOG trigger source are forgotten/set to default after each trigger. I don't think this is correct behaviour.

Example 1:
- First read the values after startup (default values),
- Set the values to something not equal to default.
- Trigger a data logging
- Read the values again: all are reset to default.

![Screenshot 2020-11-07 at 21 25 26](https://user-images.githubusercontent.com/8796121/98450944-88fffa00-2141-11eb-82fc-db3beb62cd31.png)

Example 2:
![Screenshot 2020-11-07 at 21 35 51](https://user-images.githubusercontent.com/8796121/98450945-8a312700-2141-11eb-8c01-597915fdb4ae.png)

**Comment by prasimix** [comment]
Currently we intentionally reset dlog settings after dlog finished. We'll change that, and use `*RST` to perform reset of dlog settings.

**Comment by mvladic** [comment]
Also, we are adding SCPI command `SENSe:DLOG:CLEar` to reset only DLOG settings.

All existing MicroPython scripts that are doing DLOG will be modified to call this SCPI command.

**Comment by fietser28** [comment]
Scripts were changed, but there version numbers not increased. Was this intentional?

**Comment by mvladic** [comment]
The version number is increased in the scripts-catalog.json. Where else was it supposed to increase?

**Comment by prasimix** [comment]
Fixed
