### ISSUE TITLE
Log configuration GUI 

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#118]
The log configuation menu is missing the possibility to specify a trigger. 
The menu is also not consistent with the other menu's of the bottom row: 
- It is a popup/overlay menu up instead a full screen menu
- The Cancel button doesn't really cancel your changes it just goes back to the main menu. There is no conformation/cancel option like on other settings menu's.

Below a suggestion how this can be solved:
![Screenshot 2020-11-08 at 16 42 18](https://user-images.githubusercontent.com/8796121/98469771-e481c480-21e1-11eb-99ce-bf6a0550a7d7.png)

The changes I made to the screen:
- full screen with a container at the bottom with a home, OK and cancel option. Just like other screens
- removed cancel button, not needed anymore.
- added a trigger button. In my idea this should to go a screen where you set the trigger options for the logging. This screen should be almost the same as the trigger screen of a channel.
- a blank filename causes a filename with a timestamp. Show it like this.

If triggering of data logging is recurring maybe there should also be options how to handle the filename (if it is not a timestamp): replace the file, add an auto increment number or maybe append to the same file?
![Screenshot 2020-11-08 at 17 10 53](https://user-images.githubusercontent.com/8796121/98470402-98d11a00-21e5-11eb-9e39-e7eccb7af7a6.png)

**Comment by mvladic** [comment]
Proposed new SCPI commands and queries:

- `SENSe:DLOG:FUNCtion:DIGital[:INPut] {pin}, {enable}[, {channel}]`
- `SENSe:DLOG:FUNCtion:DIGital[:INPut]? {pin}[, {channel}]`

**Comment by prasimix** [comment]
The last set color is used to mark all channels. For example, I set the magenta on the DCP module in slot 2 and the same color is used to display the DCP module parameters on slot 1:

![dlog channel color](https://user-images.githubusercontent.com/15106476/106316510-28c6b300-626d-11eb-91a0-1da98b8935b1.jpg)

**Comment by prasimix** [comment]
Fixed
