### ISSUE TITLE
Low current values presentation in DLOG viewer

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#123]
Current values in DLOG viewer are rounded to 1 mA which is not acceptable for data acquired in low current range.

**Comment by fietser28** [comment]
I think only the settings of the scales is limited. If I use view data option from the cap reform script, values below 1mA are shown:

![dlog-capreform](https://user-images.githubusercontent.com/8796121/99876295-2bb28100-2bf6-11eb-8074-3e48fa93c823.jpg)
In this case the script set the min/max values of the current from 0.0 to 200uA and that works. Not the offset and div are rounded to 0. If uA was shown it would probably say -200 (or -0.2 mA). Div is same.

If I start changing the scales (Div:) in the GUI it immediately limits me to the 1mA.

Tested on the unreleased 1.6 version.

**Comment by prasimix** [comment]
Cap reform script returns error. It requires an investigation before testing the reported problem can continue: 

![cap reform err2](https://user-images.githubusercontent.com/15106476/106317342-7e4f8f80-626e-11eb-85d1-c7e2013835d1.jpg)

**Comment by prasimix** [comment]
Test configuration: DCP in slot 1 and 2, SMX in slot 3. It is enough to tap on `Capacitor Max Voltage:` field to get previously reported error.
![cap reform err3](https://user-images.githubusercontent.com/15106476/106318037-7c3a0080-626f-11eb-8ee5-f40eb73892d4.jpg)

**Comment by prasimix** [comment]
I didn't use the latest script version, but on v1.3 we still have some issue with "phantom" OVP trip

**Comment by prasimix** [comment]
Fixed
