### ISSUE TITLE
Negative number input problem (in DLOG offset)

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#127]
Relating to #123 but different issue. It's probably generic for all negative number input.

In the offset adjustment of the DLOG viewer you can add negative number. Doing so wil display a mixed up number:
![negative number inpu](https://user-images.githubusercontent.com/8796121/99877297-53f1ae00-2bfd-11eb-8770-a051ac9fd857.jpg)
This is just one example.

**Comment by prasimix** [comment]
Fixed
