### ISSUE TITLE
Keyboard Shift/Symbol Order

### ISSUE THREAD

**Issue by willg** [eez-open/modular-psu-firmware#137]
On firmware release v1.5 it appears the keyboard shift/symbol key (highlighted in the yellow box in the image below) seems to be out of order with they keyboard I would expect to be displayed next.  As seen in the image below, the keyboard starts with the key displaying `sym`, but after the key is pressed the all-caps keyboard is displayed.  

![textFontSelection](https://user-images.githubusercontent.com/20484529/104114354-ef261a80-5346-11eb-9374-7dc32371dcac.png)

Other elements of the BB3 GUI with more than 2 options of selection (notably uA/mA/A seen below) behave the way I expect.  
![ampSelection](https://user-images.githubusercontent.com/20484529/104114495-6f00b480-5348-11eb-835a-678c452d8f3d.png)

**Comment by prasimix** [comment]
Fixed
