### ISSUE TITLE
Some ramp & delay settings cause a reboot

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#141]
Some combinations of ramps and delays cause the BB3 to reboot during the execution of the given ramp/delays. 
- For a given setting the reboot happens at the same time (reproducable)
- I could not find a relation between settings and when and if a reboot happens.

2 setups are attached one working and one causing a reboot. Only the voltage ramp of the second channel is changed.
![Ramp-delay-works](https://user-images.githubusercontent.com/8796121/104824227-4bf66900-5850-11eb-9c44-12692a5a62e1.jpg)
![Ramp-delay-reboots](https://user-images.githubusercontent.com/8796121/104824231-4d279600-5850-11eb-9c07-d251686cfdc2.jpg)

I tested this on firmware dated 11/16/20 (1.6 development).
Same problem was confirmed on 1.5 by @mvladic.

**Comment by prasimix** [comment]
Fixed
