### ISSUE TITLE
With Rprog in DCP405 Power limit should be inactive in display and OPP setting

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#145]
When using the Rprog interface of the DCP405 the power limit is still shown as active in the GUI, but this is not enforced:
![Rprog Power1](https://user-images.githubusercontent.com/8796121/105634633-45bf4880-5e5f-11eb-8500-33eb03d57768.jpg)
In this screenshot on channel 2 36W is drawn, where the UI gives the impression 5W is the limit. I think this should be graded out, 0W or not visible in this case (just like the set voltage).

OPP still works correctly, but setting the OPP trip limit complains about the (not present) power limit too:

![Rprog OPP limit](https://user-images.githubusercontent.com/8796121/105634828-40aec900-5e60-11eb-92dc-dcb1680b3ad7.jpg)

**Comment by prasimix** [comment]
* P_LIM option should be changed to read-only and change to `RP`
* Same as above, change U_SET value that is already read-only for 0.0 V (that is somewhat confusing) to `RP`

**Comment by prasimix** [comment]
Fixed
