### ISSUE TITLE
Change Protection ("shield") icon to channel settings icon on power modules

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#146]
- [x] Change Protection ("shield") icon to module/channel settings icon on power modules to be in line with other modules look
- [x] Change Setings to shield icon only in case of protection trip
- [x] Change option "Clear and Disable" on protection trip page to "Settings" which will display Protection settings

**Comment by prasimix** [comment]
Fixed

**Comment by fietser28** [comment]
1.6-RC has different implementation: last bullet is implemented different? 
A trip shows a dialog with only a 'close' button, doesn't present the choice go to the relevant menu ("settings")?

![OPPtrip](https://user-images.githubusercontent.com/8796121/107700536-ea42e680-6cb7-11eb-89b9-b27f66615fd6.jpg)

**Comment by prasimix** [comment]
Fixed
