### ISSUE TITLE
DCM220 doesn't round off low power values

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#148]
The DCM220 current measurements <250mA are not shown on DCM220. Power is stil shown for low currents. It should also be shown as <... W (depending on measured voltage * 0,25 A )?

On attached screenshot (CH3 & CH4 are DCM220) CH3 is without anything connected. CH4 has a small load connected.

![DCM220-Power-roundoff](https://user-images.githubusercontent.com/8796121/106390989-68b3a480-63eb-11eb-97f9-f8756348c479.jpg)

It think it should show:  
CH3: <0,615W    (2,46V   * 0,25A)
CH4: <5W           (20,05V * 0,25A)

**Comment by prasimix** [comment]
The same has to be done for DCM224, too.

**Comment by prasimix** [comment]
Fixed

**Comment by fietser28** [comment]
This created a new issue #158 (the roundoff itself is working).
