### ISSUE TITLE
Clear protection not always shown in red

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#149]
I like the new clear protection look, but for me there are two inconsistencies (for some **** users like me) in the GUI:

1. I perceive the new way as 'follow the red items' (red shield, red menu item). The final 'clear protection' button should be red also to make this flow intuitive (to me). (I missed it the first time).
2. If I go into the menu's and DON'T clear the protection but for example turn the protection off and save it. Then the protection is still on, the red shield is shown on the main screen, but the corresponding menu item of the protection is not red anymore.  

Below are screenshots of my journey:
![ProtectionFlow1](https://user-images.githubusercontent.com/8796121/106392050-8d5e4b00-63f0-11eb-8670-c7272e7a782e.jpg)
I tripped OPP, changed icon and red are very clear, nice. I know were to go: push it.

![ProtectionFlow2](https://user-images.githubusercontent.com/8796121/106392053-8e8f7800-63f0-11eb-892e-07bbcfc20b7d.jpg)
Very clear where the problem is, red menu item...

![ProtectionFlow3](https://user-images.githubusercontent.com/8796121/106392054-8f280e80-63f0-11eb-9da4-0a30b62f2b08.jpg)
Here I missed the red item (clear protection). = item 1 above.

![ProtectionFlow4](https://user-images.githubusercontent.com/8796121/106392057-8fc0a500-63f0-11eb-81b8-c9c0ff2f8a91.jpg)
Know it gets interesting: If I turn of OPP protection (not clearing the protection/trip)...

![ProtectionFlow6](https://user-images.githubusercontent.com/8796121/106392058-8fc0a500-63f0-11eb-8f2b-6ccde8941636.jpg)
Back to the main menu: OPP trip is still there.

![ProtectionFlow8](https://user-images.githubusercontent.com/8796121/106392063-90f1d200-63f0-11eb-997f-c71caf0a4621.jpg)
Into the menu: The red menu is not there anymore! = item 2 above.
The OPP trip is still active.

I did not test this flow for the other protections (voltage, current, temp).
Running 1.6 development firmware.

**Comment by fietser28** [comment]
Found 2 more similar inconsistencies in different view:

![ProtectionOtherView1](https://user-images.githubusercontent.com/8796121/106395824-a07b1600-6404-11eb-9e7c-b85bd96f2923.jpg)
Screen looks good, but pressing OPP in this scenario (it is tripped/RED) will bring me to the general protection menu. If OPP is not tripped, pressing OPP will jump directly to the Power protection menu (= desired action).

![ProtectionOtherView2](https://user-images.githubusercontent.com/8796121/106395827-a244d980-6404-11eb-9957-56f6a3adc147.jpg)
Performing the same flow as above: Going to the power protection menu, not clearing the trip but disabling the OPP. and returning to the main screen: the trip is still present and indicated by the shield at the top, but the OPP is not RED anymore.

**Comment by fietser28** [comment]
Small addition to item 2: Setting the power limit ON again (still without clearing the OPP trip) will make the menu item 'power limit and OPP' red again when you visit it. 
changing other values like the level of the power limit doesn't cause this. 
It appears the menu only turns red if there is a power trip AND the power limit is on. This appears false because you can disable the protection without clearing the trip.

**Comment by prasimix** [comment]
I think we need to clear the trip of the protection we want to turn off. This will avoid the need to clear the trip afterwards.

**Comment by prasimix** [comment]
I managed to enter current calibration with OCP eanbled, and got OCP trip:

![ocp in calibration](https://user-images.githubusercontent.com/15106476/106454180-a6b3d580-648a-11eb-88c0-d717d75bec43.jpg)

**Comment by prasimix** [comment]
Fixed for now
