### ISSUE TITLE
DCM220 low value indication (<) doesn't fit in all screens

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#158]
The < character doesn't fit on CH3 in screenshot below:

![DCM220RoundoffFit](https://user-images.githubusercontent.com/8796121/107697305-5a02a280-6cb3-11eb-93de-3d5fc535b0b4.jpg)

Change it from '< 250.0 mA' to '< 250 mA'?
Probably also needed for DCM224.

**Comment by prasimix** [comment]
Fixed
