### ISSUE TITLE
Feature Request: Option to hide recording status window.

### ISSUE THREAD

**Issue by NeuralSpaz** [eez-open/modular-psu-firmware#169]
Would be nice to have an option to hide the recording status window or to place the status out of the way on some of the unused space on the chart view page. There are other good indications on the main status page that the recording in happening. 

![log2](https://user-images.githubusercontent.com/6887502/109286042-e4cbcb80-7875-11eb-9614-7e84451db09b.jpg)

As can be seen above is there is no good place to put the status without having to move it again to access another function.

**Comment by prasimix** [comment]
Added a new option under `Display settings` to make all "overlay" info visible or hidden:

![overlay](https://user-images.githubusercontent.com/15106476/122514248-ec250980-d00b-11eb-94cd-6742e8270c53.jpg)
