### ISSUE TITLE
Firmware update for modules over serial

### ISSUE THREAD

**Issue by goran-mahovlic** [eez-open/modular-psu-firmware#17]
Maybe we can use micropython to flash slaves
https://github.com/pavelrevak/stm32bl/blob/master/stm32bl.py

**Comment by goran-mahovlic** [comment]
Instead of serial we need to use micropython UART
 
[](https://docs.micropython.org/en/latest/library/machine.UART.html)

Initial version on ESP32 without STM32 connected, brakes and returns 

ConnectingException: Can't connect to MCU boot-loader

[](https://gist.github.com/goran-mahovlic/8e8cbba99de24d06450d95844f7a0bf2)

**Comment by goran-mahovlic** [comment]
import stm32flasher
address = 0x00
size = 1
stm32bl = stm32flasher.Stm32flasher(1, 115200,5)

Return ID

[Response from STM32](https://ibb.co/JspRdZs)

**Comment by prasimix** [comment]
Fixed
