### ISSUE TITLE
Clear DLOG REMark and X axis label when DLOG is started through GUI

### ISSUE THREAD

**Issue by mvladic** [eez-open/modular-psu-firmware#171]

**Comment by prasimix** [comment]
Test procedure needed.

**Comment by mvladic** [comment]
First, make some DLOG using SCPI, for example:

```
SENS:DLOG:TRAC:X:UNIT VOLT
SENS:DLOG:TRAC:X:SCAL LIN
SENS:DLOG:TRAC:X:STEP 1
SENS:DLOG:TRAC:X:RANG:MIN 0
SENS:DLOG:TRAC:X:RANG:MAX 40
SENS:DLOG:TRAC:X:LAB "X-Axis label"

SENS:DLOG:TRAC:Y1:UNIT AMPE
SENS:DLOG:TRAC:Y:SCAL LIN
SENS:DLOG:TRAC:Y1:RANG:MIN 0
SENS:DLOG:TRAC:Y1:RANG:MAX 5
SENS:DLOG:TRAC:Y1:LAB "Y-Axis label"

SENS:DLOG:TRAC:REM "Testing #171"
INIT:DLOG:TRAC "/Recordings/test_171.dlog"
SENSe:DLOG:TRAC 1
SENSe:DLOG:TRAC 2
SENSe:DLOG:TRAC 3
SENSe:DLOG:TRAC 4
SENSe:DLOG:TRAC 5

ABOR:DLOG

MMEM:UPLOAD? "/Recordings/test_171.dlog"
```
Here is the result:

![image](https://user-images.githubusercontent.com/449788/121489906-d47acf00-c9d4-11eb-8240-e53103e54e5e.png)

Now, make some DLOG using GUI and transfer it to the Studio:

![image](https://user-images.githubusercontent.com/449788/121490028-f1170700-c9d4-11eb-8b06-2e9f32b3f602.png)

No DLOG remark or Axis labels should be visible from previous DLOG.

**Comment by prasimix** [comment]
The test passed, however I found on the screen an abundance of decimals for DLOG generated using SCPI commands, which need to be fixed:

![dlog decimals](https://user-images.githubusercontent.com/15106476/121491568-5cada400-c9d6-11eb-87b2-4860ce3e1242.png)

**Comment by prasimix** [comment]
Fixed
