### ISSUE TITLE
Step menu allows negative delay setting with encoder

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#174]
If you use the encoder to change the delay in the step menu of the DCP405 it doesn't honour the minimum value (4ms?), but allows you to even to negative. See screenshots.

![stepnegativedelay2](https://user-images.githubusercontent.com/8796121/113046607-8cebf180-91a0-11eb-9826-c15d9e347caa.jpg)
![stepnegativedelay](https://user-images.githubusercontent.com/8796121/113046616-8eb5b500-91a0-11eb-90a6-050c3b2a316d.jpg)

Entering the value with virtual keyboard enforces the correct lower limits.

**Comment by prasimix** [comment]
I can reproduce even worse behavior: it will restart my BB3 (tested with MCU r3B3, latest unpublished 1.7 firmware)

**Comment by prasimix** [comment]
Fixed
