### ISSUE TITLE
Dlog window at bottom of screen causes flashing at the top

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#178]
Minor GUI glitch:
If I move the white overlay windows of dlog to the bottom of the screen then the top of the screen starts to flash. It looks like the flash only happens when the screen is updated.

I assume the shadow of the white dialog flips to the top.
I'm unable to capture it with a screenshot (doesn't show the flash). 

This is the screenshot when the flashing is happening:
![overlayshadow](https://user-images.githubusercontent.com/8796121/113509891-3e4fa600-9558-11eb-800f-2ce9481e3a19.jpg)

Using firmware 1.6.1

**Comment by prasimix** [comment]
Fixed
