### ISSUE TITLE
SCPI via UART

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#19]
Accepting SCPI commands via UART will enables simple device without USB or Ethernet support to communicate and control BB3.

- [x] Add BOOKmark mode to `SYSTem:COMMunicate:UART:MODE`

**Comment by mvladic** [comment]
Add SCPI command to transmit ASCII string through UART, for example:

`SYSTem:COMMunicate:UART:TRANsmit {string}`

**Comment by prasimix** [comment]
Add an example of how to control one BB3 with another via UART (something simple, e.g. setting the voltage and output to ON state).

**Comment by prasimix** [comment]
> Add an example of how to control one BB3 with another via UART (something simple, e.g. setting the voltage and output to ON state).

An [example](https://github.com/eez-open/modular-psu-firmware/blob/master/docs/examples/arduino_dlog_bookmarks/arduino_dlog_bookmarks.ino), see also short [video](https://www.youtube.com/watch?v=337BuP4VSWc).

Fixed

**Comment by prasimix** [comment]
We need configurable communication params via GUI and SCPI. For SCPI we can use the following commands:

`SYSTem:COMMunicate:UART:BAUD (9600, 19200, 38400, ... )`
`SYSTem:COMMunicate:UART:PARIty`
`SYSTem:COMMunicate:UART:DATA`
`SYSTem:COMMunicate:UART:STOP`

**Comment by prasimix** [comment]
Fixed
