### ISSUE TITLE
"Wrong thread 6" message when limit is set below set level via SCPI and GUI (volt or current) on DCP405

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#203]
If I set the limit of current or voltage below the current set level via SCPI an error message appears on the screen.
The set level is reduces to the limit correctly. 

SCPI Example what I did, right after a fresh start:
![Screenshot 2021-06-06 at 12 49 49](https://user-images.githubusercontent.com/8796121/120921963-bb1d0e80-c6c6-11eb-8f28-0e7cc02a64fa.png)
![Screenshot 2021-06-06 at 12 52 34](https://user-images.githubusercontent.com/8796121/120921965-bd7f6880-c6c6-11eb-9bc7-82a378af57d2.png)

The event is also logged:
![thread6event](https://user-images.githubusercontent.com/8796121/120921981-e6076280-c6c6-11eb-8633-82c03cb11288.jpg)

In the GUI it also happens but the dialog is not shown, but noticeable:
1. set the voltage limit to 40V => OK
2. set the voltage level to 10V => OK
3. set the voltage limit to 5V: when you press the checkmark button ONCE you can see both the set and limit values change in the background but the windows doesn't close. Pressing the checkmark a second time the dialog is closed.
4. an event 'wrong thread 6' is logged in the event log.
(this is reproducible right after a restart, so not a leftover from other tests)

Running firmware 1.6.1, al on DCP405 module. I can not reproduce this with the DCM220 so it seems DCP405 specific.

**Comment by prasimix** [comment]
Fixed
