### ISSUE TITLE
Limits on function generator values are not properly enforced/set.

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#228]
On FW 1.7-RC1:
When entering the amplitude or offset in the function generator it is possible to input impossible values/combinations.

The Min. / Max. ranges are properly checked and generate a warning on the DCP405 module. 
On the DCM220 this also creates impossible values (outside the range of the module).

In general each channel has an absolute min (Cmin) - max (Cmax) range.
When you enter:
-  the offset: The channel capabilities AND the current amplitude should both limit the range you can enter.
- the amplitude: The channel capabilities/limits AND the current offset should both limit the range you can enter.

Comparable rules apply to min/max.  

I did not check this with SCPI commands. I also didn't turn the channels on with these values.

![FG-limits1](https://user-images.githubusercontent.com/8796121/123511997-28e4a680-d685-11eb-8576-644043df3f3a.jpg)
![FG-limits2](https://user-images.githubusercontent.com/8796121/123512000-2da95a80-d685-11eb-8cbf-e1312eb71940.jpg)
![FG-limits3](https://user-images.githubusercontent.com/8796121/123512001-2e41f100-d685-11eb-9c47-a18d1e276b35.jpg)

**Comment by prasimix** [comment]
"Impossible values" will results with error on start indicating that voltage, current or power limits have been exceeded.

**Comment by fietser28** [comment]
Fixed.
