### ISSUE TITLE
Font size changes constantly

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#236]
When just below 1A the font size of the amps is changing if the numbers change:

![Numbers1](https://user-images.githubusercontent.com/8796121/124041803-e0701480-da07-11eb-8e42-9ba59ce5d41a.jpg)

![Numbers2](https://user-images.githubusercontent.com/8796121/124041809-e36b0500-da07-11eb-9e87-b6c94389eac5.jpg)

Area for Amp is probably a bit to small to fit for all numbers.
This is on firmware 1.7-RC5.

**Comment by prasimix** [comment]
Fixed
