### ISSUE TITLE
Autostart.py script support

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#240]
Add possibility to run autostart.py MicroPython script on power up/restart if its exists in /scripts folder. Add the following:
- [x] `DISPlay[:WINDow]:HOMe` command to display home page when script execution is done
- [x] Option to enable/disable execution of the script, default is disabled
- [x] Option to override script execution to stop execution of faulty script (e.g. if encoder switch is active during power up). Display message in this case like this: `Auto script execution has been skipped. Do you also want to skip all future executions?`
- [x] #214: I would like to see an auto start option if the BB3 power up or restarts, this should also be saved in profiles so you can setup different start scenarios.
- [x] #214: If an autostart script is detected, there should be a message and ‘skip’ button so the user sees this will happen and gives the option to skip the script.
- [x] Add new `SCRipt` SCPI subsystem (see below)

**Comment by fietser28** [comment]
Combine with #214?

**Comment by fietser28** [comment]
The first item also relates to #126. If the script doesn't start a dialog, but runs in background, the user cannot get control back?

To manage all these possiblities maybe an tile/menu to the systems setting where the user can manage autostart but can also manage running/closing scripts instead of  the overlay dialog?

**Comment by mvladic** [comment]
SCPI commands:

```
- SCRipt:RUN {script_file_path}
    
  Runs script file.

  {script_file_path} is quoted string. Contains a full path to the script file, for example: "/Scripts/Hello world.py"

- SCRipt:RECall {script_file_path}
- SCRipt:RECall?

  Sets/selects auto run script. 

  {script_file_path} is quoted string. Contains a full path to the script file, for example: "/Scripts/AutoStart.py"

  Query returns selected auto run script or "" if none selected.

- SCRipt:RECall:CONFirmation
- SCRipt:RECall:CONFirmation?

  Enables/disables confirmation popup.

```

**Comment by mvladic** [comment]
To stop currently running script that got stuck you can also press both encoder and user switch from the front panel.

**Comment by fietser28** [comment]
Are SCRipt:RECall and CONFirmation part of the profile. E.g. selecting a different profile also sets a different script?

**Comment by mvladic** [comment]
Yes.

**Comment by fietser28** [comment]
Setting RECall and CONFirmation will be possible in the profile settings dialog? 
Is this a good place to add this there?

**Comment by mvladic** [comment]
We added a new Script section in Settings:

![image](https://user-images.githubusercontent.com/449788/124577194-51229100-de4d-11eb-83c1-0580dd4d42e0.png)

![image](https://user-images.githubusercontent.com/449788/124577265-63043400-de4d-11eb-9603-fd35188b28d2.png)

**Comment by mvladic** [comment]
This is in case when auto recall is not enabled:

![image](https://user-images.githubusercontent.com/449788/124577454-9050e200-de4d-11eb-9aa0-a5ed137e1761.png)

**Comment by prasimix** [comment]
Fixed

**Comment by fietser28** [comment]
Small UI inconsistency: If you change the parameters in the dialog then there doesn't appear a 'cancel' / 'ok' button on the status bar to confirm. Most other settings menu's have this workflow. 

Tested on FW 1.7.1-RC1.

**Comment by prasimix** [comment]
You're right. We are not 100% consistent on this issue. Perhaps we should open a new issue and list there all places where we're missing confirmation.
