### ISSUE TITLE
Feature request: warning when enabling channel onto live battery

### ISSUE THREAD

**Issue by brianbienvenu** [eez-open/modular-psu-firmware#255]
Enabling a DCP405 channel attached to a "high-energy" load (eg, 12V SLA battery) will invariably cause the HW OVP to fire the triac, and hence blow F2. I think this is due BB3 ramping up the output voltage, whilst the battery voltage is already present. In cases where there is already a supply present, a warning could be given to the end user.

This is predicated on the voltage at the terminals being available to the BB3, as per https://github.com/eez-open/modular-psu-firmware/issues/254

**Comment by prasimix** [comment]
Fixed

**Comment by brianbienvenu** [comment]
Thanks, that seems like a good resolution.
