### ISSUE TITLE
EEZ flow Progressbar overflows

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#274]
If the data input of the progress bar is > 100 it will happily draw a larger progressbar. :-(

This is on the screen of the BB3, studio shows a correct progress bar:
![progressbar](https://user-images.githubusercontent.com/8796121/138531483-9f561230-f339-4867-85cf-b5710de86290.jpg)

**Comment by fietser28** [comment]
Still present:
![image](https://user-images.githubusercontent.com/8796121/140518110-047e340b-6b01-4110-94b1-862faaed9e1e.png)
On BB3:
![image](https://user-images.githubusercontent.com/8796121/140518139-e3605e8b-1e12-4e92-8078-e771e9f76579.png)

**Comment by mvladic** [comment]
Should be fixed now.

**Comment by prasimix** [comment]
Fixed
