### ISSUE TITLE
EEZ Flow empty select causes restart of BB3

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#276]
I noticed an empty select causes a restart of the BB3 when the flow is started.

Just adding a single case to the list seems to fix the problem. This doesn't generate an error in studio. So either the firmware  should  check for this and/or studio should generate a warning/error.

Example, the offending select is in the page Load:
[ELLoadAnalog1.eez-project.zip](https://github.com/eez-open/modular-psu-firmware/files/7403533/ELLoadAnalog1.eez-project.zip)

Firmware: 1.8-alpha

**Comment by prasimix** [comment]
Fixed
