### ISSUE TITLE
Writing a string to a variable doesn't work

### ISSUE THREAD

**Issue by fietser28** [eez-open/modular-psu-firmware#278]
Retreiving a string via a SCPI action or from a constant and trying to store it in a variable (via set variable action) doesn't work for global structs or local strings.

Local variable locallabelstring doesn't get updated if the selected set variable action gets executed (2 examples):
![image](https://user-images.githubusercontent.com/8796121/138605884-2799296e-53e1-43ab-ba1e-f68590e311fa.png)
![image](https://user-images.githubusercontent.com/8796121/138606071-53a7c3ff-2495-422f-a1e3-3523855e7d86.png)

Related to, but a separate problem: #277

**Comment by prasimix** [comment]
Fixed
