### ISSUE TITLE
Auto-recall fails when trigger is set to LIST

### ISSUE THREAD

**Issue by fusedFET** [eez-open/modular-psu-firmware#316]
Hi, 
on fw v1.7.5 I encounter following issue:

- Ensure Auto-recall on power on is ON
- Setup channel 1 (DCP405 R2B11): Trigger List,  Step 1 5v 190mA 555s
- Flip the power switch OFF, wait a few seconds
- Flip the power switch ON
- "Recall from profile not possible" message appears, all settings are reset.

**Comment by prasimix** [comment]
Fixed
