### ISSUE TITLE
Module labeling

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#75]
Reported by @danielbriggs

_Is it possible to label the channels with text? I couldn't find a way, nor any mention in the manual. `DCM220 #4` is a great default... but would be nice to have the option to put useful labels on things that persist through power cycles, (or even profile based?) especially when lots of rails going on._

* Limit module label length to 10 characters
* In addition add border in selected module color for better separation between modules content

**Comment by mvladic** [comment]
Proposed new SCPI commands and queries for slot, channel and pin labeling:

- `SYSTem:SLOT:LABel {slot}, {label}`
	`{label}` is quoted string, min length is 0, max length is 8. If length is 0 (empty string `""`) then label is reset to the default value.

- `SYSTem:SLOT:LABel? {slot}`

- `SYSTem:SLOT:COLor {slot}, {color}`
	`{color}` is value between 0 and 24. If value is 0 then color is reset to the default value.

- `SYSTem:SLOT:COLor? {slot}`

- `SYSTem:CHANnel:LABel {channel}, {label}`
- `SYSTem:CHANnel:LABel? {channel}`
	`{label}` max length for power channels is 8 and for all other channels is 5.

- `SYSTem:CHANnel:COLor {channel}, {color}`
- `SYSTem:CHANnel:COLor? {channel}`

- `SYSTem:CHANnel:PIN:LABel {channel}, {pin}, {label}`
	This is used for digital inputs and digital outputs on MIO168 where each pin can have different label. Allowed `{pin}` range is from 1 to 8. `{label}` max length is 5.
- `SYSTem:CHANnel:PIN:LABel? {channel}, {pin}`

Color table:

|No.|Hex|Color|
|---|---|---|
|1|#d4c36b|![#f03c15](https://via.placeholder.com/35/d4c36b/000000?text=+)|
|2|#9fdd9a|![#f03c15](https://via.placeholder.com/35/9fdd9a/000000?text=+)|
|3|#73bdd8|![#f03c15](https://via.placeholder.com/35/73bdd8/000000?text=+)|
|4|#d971ca|![#f03c15](https://via.placeholder.com/35/d971ca/000000?text=+)|
|5|#dbafea|![#f03c15](https://via.placeholder.com/35/dbafea/000000?text=+)|
|6|#adaaf9|![#f03c15](https://via.placeholder.com/35/adaaf9/000000?text=+)|
|7|#f44336|![#f03c15](https://via.placeholder.com/35/f44336/000000?text=+)|
|8|#e91e63|![#f03c15](https://via.placeholder.com/35/e91e63/000000?text=+)|
|9|#9c27b0|![#f03c15](https://via.placeholder.com/35/9c27b0/000000?text=+)|
|10|#673ab7|![#f03c15](https://via.placeholder.com/35/673ab7/000000?text=+)|
|11|#3f51b5|![#f03c15](https://via.placeholder.com/35/3f51b5/000000?text=+)|
|12|#2196f3|![#f03c15](https://via.placeholder.com/35/2196f3/000000?text=+)|
|13|#03a9f4|![#f03c15](https://via.placeholder.com/35/03a9f4/000000?text=+)|
|14|#00bcd4|![#f03c15](https://via.placeholder.com/35/00bcd4/000000?text=+)|
|15|#009688|![#f03c15](https://via.placeholder.com/35/009688/000000?text=+)|
|16|#4caf50|![#f03c15](https://via.placeholder.com/35/4caf50/000000?text=+)|
|17|#8bc34a|![#f03c15](https://via.placeholder.com/35/8bc34a/000000?text=+)|
|18|#cddc39|![#f03c15](https://via.placeholder.com/35/cddc39/000000?text=+)|
|19|#ffeb3b|![#f03c15](https://via.placeholder.com/35/ffeb3b/000000?text=+)|
|20|#ffc107|![#f03c15](https://via.placeholder.com/35/ffc107/000000?text=+)|
|21|#ff9800|![#f03c15](https://via.placeholder.com/35/ff9800/000000?text=+)|
|22|#ff5722|![#f03c15](https://via.placeholder.com/35/ff5722/000000?text=+)|
|23|#795548|![#f03c15](https://via.placeholder.com/35/795548/000000?text=+)|
|24|#607d8b|![#f03c15](https://via.placeholder.com/35/607d8b/000000?text=+)|

**Comment by prasimix** [comment]
Move this option from `System info` page to `Display` page

**Comment by prasimix** [comment]
When choosing a color, we should mark which color is currently selected.

**Comment by prasimix** [comment]
Fixed

**Comment by fietser28** [comment]
If I have custom label names set (DCP405 in slot 1 and 2): After turning series coupling on and off the custom label names are forgotten/reset to the default module names.

Tested on 1.6-RC.

**Comment by prasimix** [comment]
Fixed
