### ISSUE TITLE
Option to lock set and limit current

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#8]
Add new GUI feature that current limit is "locked" (follow) set current. The result will be that on bar graph views current full scale will be always programmed current.

![lock limit](https://user-images.githubusercontent.com/15106476/32236617-fc44c59e-be62-11e7-85df-ac7ff9df4ed0.png)

**Comment by fietser28** [comment]
I think this is implemented now by #78?

**Comment by prasimix** [comment]
Fixed
