### ISSUE TITLE
SCPI query for current measurement includes units symbol

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#83]
Reported by Apo:

* _MEAS? returns "10.0", MEAS:CURR? "0.5A"_

**Comment by mvladic** [comment]
This is already fixed in #23 and released with firmware version 1.1.

P.S. Just to be sure this is clear let me state that `meas?` is short for `meas:volt?`

**Comment by prasimix** [comment]
Duplicate
