### ISSUE TITLE
Encoder step values for voltage and current for DCP405

### ISSUE THREAD

**Issue by mvladic** [eez-open/modular-psu-firmware#87]
- Add 0.5 V as a new step, change 10 mV to 25 mV.
- Add 50 mA as a new step, change 1 mA to 2.5 mA (Hi range)
- Add 50 uA as a new step, change 10 uA to 25 uA (Low range)

Reported by @IanJ:
- Could you add 0.5V for a valid step change. I for one would find that useful as 100mV maybe too small, 1V too big.

**Comment by prasimix** [comment]
Fixed
