### ISSUE TITLE
Current readout in YT-view and dark theme could be more readable

### ISSUE THREAD

**Issue by Cat-Ion** [eez-open/modular-psu-firmware#97]
When viewed from an angle, the current readout in YT-view can be too hard to read, while everything else is fine:

![image](https://user-images.githubusercontent.com/443968/97120113-35d78180-1715-11eb-9d81-55850b69f346.png)

This is also the case with lightness and brightness turned to their maximum values. I realize that the light is in a... somewhat pessimal position for this, but since everything else is readable I figured it'd be worth a mention. Just making it the same colour as 'OFF' would probably be fine.

**Comment by prasimix** [comment]
Fixed

**Comment by kliment** [comment]
Hmm, how does that commit fix this issue? It seems it was meant to fix another one.

**Comment by mvladic** [comment]
For the reference, I was mistakenly commited https://github.com/eez-open/modular-psu-firmware/commit/44c87cadac2e0811c89da14991cec917d4651f7e with description "#97" 6 days ago which is unrelated to this issue.
