### ISSUE TITLE
DCP405: With 'Best' current scaling, allow using 5 uA steps while in low current range

### ISSUE THREAD

**Issue by Cat-Ion** [eez-open/modular-psu-firmware#98]
When the current scaling is set to 'Best' and the current is <50 mA, rotating the encoder uses 0.5 mA steps, while 5 uA steps should be possible.

**Comment by prasimix** [comment]
If set current is 50 mA or less when change current range from `Best` to `High`, it keeps to use uA instead of mA to display when load is not connected. OE state recycling is needed to use mA.

**Comment by prasimix** [comment]
Fixed
