### ISSUE TITLE
Hide hidden system folders on µSD card.

### ISSUE THREAD

**Issue by danielbriggs** [eez-open/modular-psu-firmware#99]
Is it possible to get the built in BB3 file manager to hide hidden folders?
When you plug one of the SD cards into a Windows PC you get "System Volume Information" folder created. And plugged into OS X you get lots of crap: ".Trashes", ".fseventsd", ".Spotlight...." etc.
It would just offer less clutter to the nice file manager view you have made.

**Comment by prasimix** [comment]
Files and folders with System and Hidden attributes are not displayed anymore.

**Comment by prasimix** [comment]
I think that .Trash-1000 should be hidden:

![hidden folder](https://user-images.githubusercontent.com/15106476/98368387-8d3ff080-2037-11eb-81df-b440029959a2.jpg)

**Comment by prasimix** [comment]
Fixed
